export { LoginPage } from './LoginPage';
export { RegisterPage } from './RegisterPage';
export { DashboardPage } from './DashboardPage';
export { DocumentsPage } from './DocumentsPage';
export { DocumentDetailPage } from './DocumentDetailPage';
export { UploadPage } from './UploadPage';
export { ChatPage } from './ChatPage';
export { HistoryPage } from './HistoryPage';
export { SettingsPage } from './SettingsPage';
